export const ApplicationComponents = {
  DataSource: Symbol.for('DataSource'),
  Redis: Symbol.for('Redis'),
  HealthService: Symbol.for('HealthService'),
  HealthController: Symbol.for('HealthController'),
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  AuthService: Symbol.for('AuthService'),
  AuthController: Symbol.for('AuthController'),
  OrderRepository: Symbol.for('OrderRepository'),
  OrderService: Symbol.for('OrderService'),
  OrderController: Symbol.for('OrderController'),
  TeamService: Symbol.for('TeamService'),
  TeamController: Symbol.for('TeamController'),
};
